-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 22:59:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BibliotecaMarcosMiranad
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BibliotecaMarcosMiranad` ;

-- -----------------------------------------------------
-- Schema BibliotecaMarcosMiranad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BibliotecaMarcosMiranad` DEFAULT CHARACTER SET utf8 ;
USE `BibliotecaMarcosMiranad` ;

-- -----------------------------------------------------
-- Table `BibliotecaMarcosMiranad`.`libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaMarcosMiranad`.`libro` ;

CREATE TABLE IF NOT EXISTS `BibliotecaMarcosMiranad`.`libro` (
  `isbn` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `numeroPaginas` INT NULL,
  `fechaPublicacion` DATE NULL,
  `prestadoSiNo` VARCHAR(45) NULL,
  `fechaDevolucion` VARCHAR(45) NULL,
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMarcosMiranad`.`socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaMarcosMiranad`.`socio` ;

CREATE TABLE IF NOT EXISTS `BibliotecaMarcosMiranad`.`socio` (
  `codigoSocio` INT NOT NULL,
  `nombreSocio` VARCHAR(45) NULL,
  `apellidoSocio1` VARCHAR(45) NULL,
  `apellidoSocio2` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `sociocol` VARCHAR(45) NULL,
  PRIMARY KEY (`codigoSocio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMarcosMiranad`.`prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaMarcosMiranad`.`prestamo` ;

CREATE TABLE IF NOT EXISTS `BibliotecaMarcosMiranad`.`prestamo` (
  `isbn` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `codigoSocio` VARCHAR(45) NULL,
  `nombreSocio` VARCHAR(45) NULL,
  `apellidoSocio` VARCHAR(45) NULL,
  `fechaDevolucion` DATE NULL,
  `socio_codigoSocio` INT NOT NULL,
  `libro_isbn` INT NOT NULL,
  PRIMARY KEY (`isbn`, `socio_codigoSocio`, `libro_isbn`),
  INDEX `fk_prestamo_socio_idx` (`socio_codigoSocio` ASC) ,
  INDEX `fk_prestamo_libro1_idx` (`libro_isbn` ASC) ,
  CONSTRAINT `fk_prestamo_socio`
    FOREIGN KEY (`socio_codigoSocio`)
    REFERENCES `BibliotecaMarcosMiranad`.`socio` (`codigoSocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_libro1`
    FOREIGN KEY (`libro_isbn`)
    REFERENCES `BibliotecaMarcosMiranad`.`libro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
